### ISSUE TITLE
Need the ability to do version bump

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/nrf51-sdk#1]
@marcuschangarm wants to add files to this module as he's developing modules using the functionalities of the nordic sdk which means as he develops, he will want more and more files. He wants to be able to update nrf51-sdk as he need. This requires being able to bump version number and republish. This mean we cannot strictly use noridc's version. Personally I propose we ditch nordic's version number. We bump major version when porting a new sdk from nordic, but minor and patch version number reserved for our change. The mapping can be tracked in README.md. @rgrover can you comment on this?

**Comment by rgrover** [comment]
I agree that we cannot freeze the state of imports from the nRF-SDK. This is because:
- this is a subset of the original SDK, and we might want to include more of the original as needed.
- we'll make amendments over time to fix issues

Let's just go with semantic versioning starting with 0.0.1. The top level readme.md would clearly state the origins of the sources.

**Comment by marcuschangarm** [comment]
I'm not particularly happy with this setup. Basically, we're doing something different for the nordic again. All the other supported platforms have full driver support, even for non-mbed-hal peripherals.

https://github.com/ARMmbed/mbed-hal-silabs/tree/master/source/emlib
https://github.com/ARMmbed/mbed-hal-ksdk-mcu/tree/master/source/TARGET_KSDK_CODE
https://github.com/ARMmbed/mbed-hal-st-stm32cubef4/tree/master/source

**Comment by rgrover** [comment]
@marcuschangarm what are you proposing?

**Comment by marcuschangarm** [comment]
At least include everything from /components/drivers_nrf. And if we are not including the entire SDK, put it in https://github.com/ARMmbed/mbed-hal-nrf51822-mcu like the other platforms.

**Comment by rgrover** [comment]
right. I'm happy for everything from components/drivers_nrf to be included. @LiyouZhou please update license headers as you import files.
