### ISSUE TITLE
nrf51-sdk generates warnings for old style declarations

### ISSUE THREAD

**Issue by ghost** [ARMmbed/nrf51-sdk#10]
``` sh
yotta_modules/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/hal/nrf_delay.h:84:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
 static void __INLINE nrf_delay_us(uint32_t volatile number_of_us)
```

I tried adding that to `yotta_modules/nrf51-sdk/source/supress-warnings.cmake` but then it told me

``` sh
[97/130] Building CXX object ym/nrf51-sdk/source/CMakeFiles/nrf51-...-sdk/source/nordic_sdk/components/ble/common/ble_conn_params.cpp.o
cc1plus: warning: command line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
```

I didn't see a way to `COMPILE_FLAGS` for just C++.

**Comment by LiyouZhou** [comment]
@jrobeson This is a known issue. This style error is inherited from the Nordic sdk which uses different build system. This warning should not affect build, but it is annoying. 

We try to make as few changes to the original sdk files as possible, but you can try putting `__INLINE` to the start of the line, should make this warning go away. You can make a pull request when you have made the fix.

We are working on reducing the number of warnings to make the build process more pleasant.

**Comment by rgrover** [comment]
closing it for now. please re-open if you need further clarification

**Comment by ghost** [comment]
I didn't know  you folks were accepting those kinds of changes to the sdk files. I'll certainly submit that as a PR , if it is acceptable.

**Comment by LiyouZhou** [comment]
@jrobeson 

# Contributor agreement

For your pull request to be accepted, we will need you to agree to our [contributor agreement](https://developer.mbed.org/contributor_agreement/) to give us the necessary rights to use and distribute your contributions. (To click through the agreement create an account on mbed.com and log in.)

Please accept the agreement and let me know your mbed.com account name so I can verify. Thanks!

**Comment by ghost** [comment]
I already signed it (as per my commits to mbed/mbed) . same as my github id: jrobeson

**Comment by ghost** [comment]
I'll take a look at this again once the update to sdk 10 is merged.
