### ISSUE TITLE
Question: nrf51 and nrf52 support with nRF5 11 SDK

### ISSUE THREAD

**Issue by metc** [ARMmbed/nrf51-sdk#25]
Hello,

There are currently two repositories for the [nrf51-sdk](https://github.com/ARMmbed/nrf51-sdk) and the [nrf52-sdk](https://github.com/ARMmbed/nrf52-sdk).
What is our vision for the future: do you will support a SDK11 repository for all nRF5X devices ?

This is maybe not the right place to ask this question. Is there another channel to ask such questions ?
Thanks

**Comment by pan-** [comment]
Hello Christopher,

`nrf52-sdk` repository was not supposed to be public at this point, it is not ready yet.
In the future there will be only one repository for nrf5X-sdk and one for ble-nrf5XXXX.

**Comment by metc** [comment]
Makes sense. I am very looking forward to this.
Thank you for the clarification.

**Comment by metc** [comment]
@pan- May I ask when the `ble-nrf5XXXX` will be released and when the nRF52 will be supported ?

**Comment by pan-** [comment]
@metc We don't know yet.

**Comment by metc** [comment]
@pan- Thanks for your answer. Where will be the information publish ?

**Comment by pan-** [comment]
@metc certainly somewhere on developer.mbed.org

**Comment by metc** [comment]
Thanks, I am very looking forward to it :notes:

**Comment by georgeedwards** [comment]
+1 for nrf52 support :)

**Comment by yogeshk19** [comment]
Any updates regarding the nrf52 support?  Just was wondering if there is any timeline when the nrf52_dk board support made available.

Thanks,
Yogesh

**Comment by pan-** [comment]
@yogeshk19 There is no plan at the moment to support the NRF52 with mbed OS 3, but it is well supported by mbed OS 5.
