### ISSUE TITLE
nrf52-sdk support

### ISSUE THREAD

**Issue by yogeshk19** [ARMmbed/nrf51-sdk#28]
I was wondering if there are any updates when the nrf52832 drivers would be made available? Currently the nrf52_dk based platform is available in the online mbed compiler, but using the ble_api libraries generates the following error:

**"Please provide an Implementation for mbed ble"**

Can you please provide a timeline when the nrf52_sdk would be made available?

Thanks,
Yogesh

**Comment by nvlsianpu** [comment]
BLE support for nrf52 is available in mbed 5.0 which is successor of the mbed 2.0 (classic) and the mbed 3.0 (previous called mbed-os). In online compiler you can select e.g.  mbed-os-example-ble-HeartRate. In case you prefer developing in local environment (mbed command line tool or a regular IDE) you can look at https://github.com/ARMmbed/mbed-os-example-ble.

**Comment by nvlsianpu** [comment]
answered here https://github.com/ARMmbed/nrf51-sdk/issues/25 as well.
